### PR TITLE
regnie2raster

### PR DESCRIPTION
**Pull request by jamaa**
This completes regnie to raster conversion functionality as discussed in #2 

Let me know if you think I should change anything. I think pull requests can still be modified before merging. I am still learning GitHub :-)

### CODE REVIEW

**Review by Weathermann — COMMENTED** [review]
With the `Path` module we have the possibility to avoid long constructions like
`os.path.join(), os.path.exists()`
and can replace them with
```
from pathlib import Path

regnie_path = Path(dirname) / filename (str)   # construct path
Path(file_regnie).exists()
Path(file_regnie).name    # instead of basename
Path(file_regnie).open() as f:
```

suggestion:
```
self._file = Path(file_regnie)
...
self._file. <- access methods
```
I suggest taking this opportunity.

**Review by Weathermann — COMMENTED** [review]
`id` Is a reserved keyword that IDEs can complain about.
That was why I used `_id`. Should we better use that?

**Review by Weathermann — APPROVED** [review]

**Review by Weathermann — APPROVED** [review]

**Review by Weathermann — APPROVED** [review]

**Comment by jamaa** [comment]
I'm happy to make the changes you suggested. I will add commits to my branch. Apparently they will then show up in this pull request.

**Comment by jamaa** [comment]
A new commit has been added to use Path instead of strings.

> `id` Is a reserved keyword that IDEs can complain about. That was why I used `_id`. Should we better use that?

where is `id` used? I couldn't find it...

**Review by Weathermann — APPROVED** [review]
wonderful

**Review by Weathermann — APPROVED** [review]

**Review by Weathermann — APPROVED** [review]

**Comment by Weathermann** [comment]
> A new commit has been added to use Path instead of strings.
> 
> > `id` Is a reserved keyword that IDEs can complain about. That was why I used `_id`. Should we better use that?
> 
> where is `id` used? I couldn't find it...

Ah, I must have seen old changes (From line 224 in `classes/Regnie2CSV.py`).
The whole CSV functionality (where we needed _id) has been removed. 
=> OK :+1:

**Pull request merged**
